/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.ccel-coordinator.toml --env-file=/dev/null --include-runtime=false ccel-coordinator-configuration.d.ts` (hash: a17100c6ccfa332cec17972e4f499b3d)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/ccel-coordinator-worker");
		durableNamespaces: "CcelGlobalCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
