#!/usr/bin/env bash
#
# Export theologai.db to D1-compatible SQL files.
#
# Uses SQLite quote() to avoid unistr() (unsupported by D1).
# Large tables (morphology, cross_references) are chunked at 50K rows.
# D1 limit: ~10MB per file, ~100KB per statement.
#
# Usage: bash scripts/export-for-d1.sh
#
# Output: scripts/d1-migration/01-schema.sql ... 09-fts-rebuild.sql

set -euo pipefail

DB="data/theologai.db"
OUT="scripts/d1-migration"

if [ ! -f "$DB" ]; then
  echo "Error: $DB not found. Run 'npm run build:db' first."
  exit 1
fi

rm -f "$OUT"/*.sql
echo "Exporting from $DB → $OUT/"

# Helper: export rows using quote() to avoid unistr()
# Usage: export_table TABLE_NAME "col1,col2,..." "SELECT ... " LIMIT OFFSET
export_quoted() {
  local table=$1 cols=$2 query=$3
  sqlite3 "$DB" "SELECT 'INSERT INTO ${table}(${cols}) VALUES(' || $(
    # Build quote(col1) || ',' || quote(col2) || ... from column list
    echo "$cols" | tr ',' '\n' | while IFS= read -r col; do
      echo "quote(${col})"
    done | paste -sd'|' - | sed "s/|/ || ',' || /g"
  ) || ');' FROM (${query});"
}

# ─── 01: Schema (regular tables only, no FTS) ───────────────────────

echo "  01-schema.sql"
cat > "$OUT/01-schema.sql" << 'SCHEMASQL'
-- TheologAI D1 Schema (regular tables)
-- Generated by scripts/export-for-d1.sh

CREATE TABLE IF NOT EXISTS cross_references (
    from_verse TEXT NOT NULL,
    to_verse TEXT NOT NULL,
    votes INTEGER NOT NULL,
    PRIMARY KEY (from_verse, to_verse)
);

CREATE TABLE IF NOT EXISTS strongs (
    strongs_number TEXT PRIMARY KEY,
    testament TEXT NOT NULL,
    lemma TEXT NOT NULL,
    transliteration TEXT,
    pronunciation TEXT,
    definition TEXT NOT NULL,
    derivation TEXT
);

CREATE TABLE IF NOT EXISTS morphology (
    book TEXT NOT NULL,
    chapter INTEGER NOT NULL,
    verse INTEGER NOT NULL,
    position INTEGER NOT NULL,
    word_text TEXT NOT NULL,
    lemma TEXT NOT NULL,
    strongs_number TEXT,
    morph_code TEXT,
    gloss TEXT,
    PRIMARY KEY (book, chapter, verse, position)
);

CREATE TABLE IF NOT EXISTS stepbible_lexicons (
    strongs_number TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    extended_data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    date TEXT,
    metadata TEXT
);

CREATE TABLE IF NOT EXISTS document_sections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id TEXT NOT NULL,
    section_number TEXT,
    title TEXT,
    content TEXT NOT NULL,
    topics TEXT
);

CREATE TABLE IF NOT EXISTS morph_codes (
    code TEXT PRIMARY KEY,
    expansion TEXT NOT NULL
);
SCHEMASQL

# ─── 02: Small tables (morph_codes, documents) ──────────────────────

echo "  02-small-tables.sql"
{
  echo "-- morph_codes + documents"
  export_quoted morph_codes "code,expansion" "SELECT * FROM morph_codes"
  export_quoted documents "id,title,type,date,metadata" "SELECT * FROM documents"
} > "$OUT/02-small-tables.sql"

# ─── 03: document_sections (split oversized rows) ───────────────────
# One section (council-of-trent #350) is 312KB — exceeds D1 statement limit.
# Export normal sections in 03a, oversized ones individually in 03b+.

DS_COLS="id,document_id,section_number,title,content,topics"
DS_COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM document_sections")
DS_LARGE=$(sqlite3 "$DB" "SELECT COUNT(*) FROM document_sections WHERE LENGTH(content) > 90000")

echo "  03-document-sections.sql (${DS_COUNT} rows, ${DS_LARGE} oversized)"
{
  echo "-- document_sections (rows with content <= 90KB)"
  export_quoted document_sections "$DS_COLS" \
    "SELECT * FROM document_sections WHERE LENGTH(content) <= 90000"
} > "$OUT/03-document-sections.sql"

# Export oversized sections: INSERT with truncated content, then UPDATE to append rest
# D1 statement limit is ~256KB; we use 80KB chunks to stay well under.
CONTENT_CHUNK=80000
if [ "$DS_LARGE" -gt 0 ]; then
  IDX=0
  sqlite3 "$DB" "SELECT id FROM document_sections WHERE LENGTH(content) > 90000;" | while read -r ROW_ID; do
    PADDED=$(printf "%02d" $IDX)
    OUTFILE="$OUT/03-document-sections-large-${PADDED}.sql"
    CONTENT_LEN=$(sqlite3 "$DB" "SELECT LENGTH(content) FROM document_sections WHERE id = ${ROW_ID};")
    CHUNKS=$(( (CONTENT_LEN + CONTENT_CHUNK - 1) / CONTENT_CHUNK ))
    echo "  03-document-sections-large-${PADDED}.sql (row id=${ROW_ID}, ${CONTENT_LEN} bytes → ${CHUNKS} chunks)"
    {
      echo "-- document_sections oversized row id=${ROW_ID} (${CONTENT_LEN} bytes)"
      # First chunk: INSERT with first 80KB of content
      sqlite3 "$DB" "SELECT 'INSERT INTO document_sections(id,document_id,section_number,title,content,topics) VALUES(' || quote(id) || ',' || quote(document_id) || ',' || quote(section_number) || ',' || quote(title) || ',' || quote(substr(content,1,${CONTENT_CHUNK})) || ',' || quote(topics) || ');' FROM document_sections WHERE id = ${ROW_ID};"
      # Remaining chunks: UPDATE to append
      for c in $(seq 1 $((CHUNKS - 1))); do
        OFFSET=$(( c * CONTENT_CHUNK + 1 ))
        sqlite3 "$DB" "SELECT 'UPDATE document_sections SET content = content || ' || quote(substr(content,${OFFSET},${CONTENT_CHUNK})) || ' WHERE id = ${ROW_ID};' FROM document_sections WHERE id = ${ROW_ID};"
      done
    } > "$OUTFILE"
    IDX=$((IDX + 1))
  done
fi

# ─── 04: strongs ─────────────────────────────────────────────────────

STRONGS_COLS="strongs_number,testament,lemma,transliteration,pronunciation,definition,derivation"
echo "  04-strongs.sql ($(sqlite3 "$DB" "SELECT COUNT(*) FROM strongs") rows)"
{
  echo "-- strongs"
  export_quoted strongs "$STRONGS_COLS" "SELECT * FROM strongs"
} > "$OUT/04-strongs.sql"

# ─── 05: stepbible_lexicons ──────────────────────────────────────────

echo "  05-stepbible-lexicons.sql ($(sqlite3 "$DB" "SELECT COUNT(*) FROM stepbible_lexicons") rows)"
{
  echo "-- stepbible_lexicons"
  export_quoted stepbible_lexicons "strongs_number,source,extended_data" \
    "SELECT * FROM stepbible_lexicons"
} > "$OUT/05-stepbible-lexicons.sql"

# ─── 06-xx: cross_references (chunked at 50K rows) ──────────────────

XREF_COLS="from_verse,to_verse,votes"
XREF_COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM cross_references")
CHUNK=50000
XREF_CHUNKS=$(( (XREF_COUNT + CHUNK - 1) / CHUNK ))

echo "  06-cross-references (${XREF_COUNT} rows → ${XREF_CHUNKS} chunks)"
for i in $(seq 0 $((XREF_CHUNKS - 1))); do
  OFFSET=$((i * CHUNK))
  PADDED=$(printf "%02d" $i)
  OUTFILE="$OUT/06-cross-references-${PADDED}.sql"
  {
    echo "-- cross_references chunk $((i+1))/${XREF_CHUNKS} (offset ${OFFSET})"
    export_quoted cross_references "$XREF_COLS" \
      "SELECT * FROM cross_references ORDER BY from_verse, to_verse LIMIT $CHUNK OFFSET $OFFSET"
  } > "$OUTFILE"
done

# ─── 07-xx: morphology (chunked at 50K rows) ────────────────────────

MORPH_COLS="book,chapter,verse,position,word_text,lemma,strongs_number,morph_code,gloss"
MORPH_COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM morphology")
MORPH_CHUNKS=$(( (MORPH_COUNT + CHUNK - 1) / CHUNK ))

echo "  07-morphology (${MORPH_COUNT} rows → ${MORPH_CHUNKS} chunks)"
for i in $(seq 0 $((MORPH_CHUNKS - 1))); do
  OFFSET=$((i * CHUNK))
  PADDED=$(printf "%02d" $i)
  OUTFILE="$OUT/07-morphology-${PADDED}.sql"
  {
    echo "-- morphology chunk $((i+1))/${MORPH_CHUNKS} (offset ${OFFSET})"
    export_quoted morphology "$MORPH_COLS" \
      "SELECT * FROM morphology ORDER BY book, chapter, verse, position LIMIT $CHUNK OFFSET $OFFSET"
  } > "$OUTFILE"
done

# ─── 08: Indexes ─────────────────────────────────────────────────────

echo "  08-indexes.sql"
cat > "$OUT/08-indexes.sql" << 'INDEXSQL'
-- Indexes (created after data load for speed)
CREATE INDEX IF NOT EXISTS idx_xref_from ON cross_references(from_verse);
CREATE INDEX IF NOT EXISTS idx_xref_votes ON cross_references(votes DESC);
CREATE INDEX IF NOT EXISTS idx_morph_verse ON morphology(book, chapter, verse);
CREATE INDEX IF NOT EXISTS idx_morph_strongs ON morphology(strongs_number);
INDEXSQL

# ─── 09: FTS5 virtual tables ────────────────────────────────────────

echo "  09-fts-rebuild.sql"
cat > "$OUT/09-fts-rebuild.sql" << 'FTSSQL'
-- FTS5 virtual tables + populate from base tables

CREATE VIRTUAL TABLE IF NOT EXISTS strongs_fts USING fts5(
    strongs_number UNINDEXED, lemma, transliteration, definition
);

INSERT INTO strongs_fts (strongs_number, lemma, transliteration, definition)
    SELECT strongs_number, lemma, transliteration, definition FROM strongs;

CREATE VIRTUAL TABLE IF NOT EXISTS sections_fts USING fts5(
    title, content, topics
);

INSERT INTO sections_fts (title, content, topics)
    SELECT title, content, topics FROM document_sections;
FTSSQL

# ─── Summary ─────────────────────────────────────────────────────────

echo ""
echo "Done! Generated files:"
ls -lhS "$OUT"/*.sql
echo ""
TOTAL=$(du -sh "$OUT" | cut -f1)
echo "Total: $TOTAL"
echo ""
echo "Import to D1 with:"
echo '  for f in scripts/d1-migration/*.sql; do'
echo '    echo "Importing $f..."'
echo '    npx wrangler d1 execute theologai-db --remote --file="$f"'
echo '  done'
