-- Strong's Concordance Database Schema
-- Data Source: OpenScriptures Strong's Hebrew and Greek Dictionaries
-- License: Public Domain
-- Build Date: Generated by build-strongs-database.ts script

-- Main Strong's entries table
CREATE TABLE IF NOT EXISTS strongs_entries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    testament TEXT NOT NULL CHECK(testament IN ('OT', 'NT')),
    strongs TEXT NOT NULL,
    lemma TEXT NOT NULL,
    transliteration TEXT,
    pronunciation TEXT,
    definition TEXT NOT NULL,
    derivation TEXT,
    UNIQUE(testament, strongs)
);

-- Index for fast lookups by Strong's number
CREATE INDEX IF NOT EXISTS idx_strongs_lookup
ON strongs_entries(testament, strongs);

-- Index for lemma searches (future feature)
CREATE INDEX IF NOT EXISTS idx_strongs_lemma
ON strongs_entries(testament, lemma);

-- Metadata table for database information
CREATE TABLE IF NOT EXISTS metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Insert metadata (will be populated by build script)
INSERT OR REPLACE INTO metadata (key, value) VALUES
    ('version', '1.0.0'),
    ('source', 'OpenScriptures Strong''s Hebrew and Greek Dictionaries'),
    ('source_url', 'https://github.com/openscriptures/strongs'),
    ('license', 'Public Domain'),
    ('attribution', 'Open Scriptures (openscriptures.org)'),
    ('schema_version', '1'),
    ('build_date', datetime('now'));
